//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 13:42:48 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// step                           O     8 reg
// RDY_step                       O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// step_d                         I     8
// step_rst                       I     1
// EN_step                        I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkDFFSyncRstVector(CLK,
			  RST_N,

			  step_d,
			  step_rst,
			  EN_step,
			  step,
			  RDY_step);
  input  CLK;
  input  RST_N;

  // actionvalue method step
  input  [7 : 0] step_d;
  input  step_rst;
  input  EN_step;
  output [7 : 0] step;
  output RDY_step;

  // signals for module outputs
  wire [7 : 0] step;
  wire RDY_step;

  // register q
  reg [7 : 0] q;
  wire [7 : 0] q$D_IN;
  wire q$EN;

  // actionvalue method step
  assign step = q ;
  assign RDY_step = 1'd1 ;

  // register q
  assign q$D_IN = step_rst ? 8'd0 : step_d ;
  assign q$EN = EN_step ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        q <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (q$EN) q <= `BSV_ASSIGNMENT_DELAY q$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    q = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkDFFSyncRstVector

