//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 09:30:37 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_mux2x1_output              O   100
// RDY_get_mux2x1_output          O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_mux2x1_output_x            I   100
// get_mux2x1_output_y            I   100
// get_mux2x1_output_sel          I     1
//
// Combinational paths from inputs to outputs:
//   (get_mux2x1_output_x,
//    get_mux2x1_output_y,
//    get_mux2x1_output_sel) -> get_mux2x1_output
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMux2x1Vector(CLK,
		      RST_N,

		      get_mux2x1_output_x,
		      get_mux2x1_output_y,
		      get_mux2x1_output_sel,
		      get_mux2x1_output,
		      RDY_get_mux2x1_output);
  input  CLK;
  input  RST_N;

  // value method get_mux2x1_output
  input  [99 : 0] get_mux2x1_output_x;
  input  [99 : 0] get_mux2x1_output_y;
  input  get_mux2x1_output_sel;
  output [99 : 0] get_mux2x1_output;
  output RDY_get_mux2x1_output;

  // signals for module outputs
  wire [99 : 0] get_mux2x1_output;
  wire RDY_get_mux2x1_output;

  // value method get_mux2x1_output
  assign get_mux2x1_output =
	     get_mux2x1_output_sel ?
	       get_mux2x1_output_y :
	       get_mux2x1_output_x ;
  assign RDY_get_mux2x1_output = 1'd1 ;
endmodule  // mkMux2x1Vector

