//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Wed Apr  8 12:16:47 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_step                       O     1 const
// out                            O     1
// RDY_out                        O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// step_in                        I     1
// EN_step                        I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFsm3comb(CLK,
		  RST_N,

		  step_in,
		  EN_step,
		  RDY_step,

		  out,
		  RDY_out);
  input  CLK;
  input  RST_N;

  // action method step
  input  step_in;
  input  EN_step;
  output RDY_step;

  // value method out
  output out;
  output RDY_out;

  // signals for module outputs
  wire RDY_out, RDY_step, out;

  // register state
  reg [1 : 0] state;
  reg [1 : 0] state$D_IN;
  wire state$EN;

  // remaining internal signals
  wire [1 : 0] IF_step_in_THEN_1_ELSE_2___d10;

  // action method step
  assign RDY_step = 1'd1 ;

  // value method out
  assign out = state == 2'd3 ;
  assign RDY_out = 1'd1 ;

  // register state
  always@(state or IF_step_in_THEN_1_ELSE_2___d10 or step_in)
  begin
    case (state)
      2'd0: state$D_IN = step_in ? 2'd1 : 2'd0;
      2'd1, 2'd3: state$D_IN = IF_step_in_THEN_1_ELSE_2___d10;
      2'd2: state$D_IN = step_in ? 2'd3 : 2'd0;
    endcase
  end
  assign state$EN = EN_step ;

  // remaining internal signals
  assign IF_step_in_THEN_1_ELSE_2___d10 = step_in ? 2'd1 : 2'd2 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        state <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    state = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkFsm3comb

