//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 23:23:28 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_step                       O     1 const
// lfsr_out                       O     5 reg
// RDY_lfsr_out                   O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// step_reset_signal              I     1
// EN_step                        I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkLfsr5(CLK,
	       RST_N,

	       step_reset_signal,
	       EN_step,
	       RDY_step,

	       lfsr_out,
	       RDY_lfsr_out);
  input  CLK;
  input  RST_N;

  // action method step
  input  step_reset_signal;
  input  EN_step;
  output RDY_step;

  // value method lfsr_out
  output [4 : 0] lfsr_out;
  output RDY_lfsr_out;

  // signals for module outputs
  wire [4 : 0] lfsr_out;
  wire RDY_lfsr_out, RDY_step;

  // register dff0_out
  reg dff0_out;
  wire dff0_out$D_IN, dff0_out$EN;

  // register dff1_out
  reg dff1_out;
  wire dff1_out$D_IN, dff1_out$EN;

  // register dff2_out
  reg dff2_out;
  wire dff2_out$D_IN, dff2_out$EN;

  // register dff3_out
  reg dff3_out;
  wire dff3_out$D_IN, dff3_out$EN;

  // register dff4_out
  reg dff4_out;
  wire dff4_out$D_IN, dff4_out$EN;

  // remaining internal signals
  wire d__h410;

  // action method step
  assign RDY_step = 1'd1 ;

  // value method lfsr_out
  assign lfsr_out = { dff4_out, dff3_out, dff2_out, dff1_out, dff0_out } ;
  assign RDY_lfsr_out = 1'd1 ;

  // register dff0_out
  assign dff0_out$D_IN = step_reset_signal || dff1_out ;
  assign dff0_out$EN = EN_step ;

  // register dff1_out
  assign dff1_out$D_IN = !step_reset_signal && dff2_out ;
  assign dff1_out$EN = EN_step ;

  // register dff2_out
  assign dff2_out$D_IN = !step_reset_signal && d__h410 ;
  assign dff2_out$EN = EN_step ;

  // register dff3_out
  assign dff3_out$D_IN = !step_reset_signal && dff4_out ;
  assign dff3_out$EN = EN_step ;

  // register dff4_out
  assign dff4_out$D_IN = !step_reset_signal && dff0_out ;
  assign dff4_out$EN = EN_step ;

  // remaining internal signals
  assign d__h410 = dff3_out ^ dff0_out ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        dff0_out <= `BSV_ASSIGNMENT_DELAY 1'd0;
	dff1_out <= `BSV_ASSIGNMENT_DELAY 1'd0;
	dff2_out <= `BSV_ASSIGNMENT_DELAY 1'd0;
	dff3_out <= `BSV_ASSIGNMENT_DELAY 1'd0;
	dff4_out <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (dff0_out$EN) dff0_out <= `BSV_ASSIGNMENT_DELAY dff0_out$D_IN;
	if (dff1_out$EN) dff1_out <= `BSV_ASSIGNMENT_DELAY dff1_out$D_IN;
	if (dff2_out$EN) dff2_out <= `BSV_ASSIGNMENT_DELAY dff2_out$D_IN;
	if (dff3_out$EN) dff3_out <= `BSV_ASSIGNMENT_DELAY dff3_out$D_IN;
	if (dff4_out$EN) dff4_out <= `BSV_ASSIGNMENT_DELAY dff4_out$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    dff0_out = 1'h0;
    dff1_out = 1'h0;
    dff2_out = 1'h0;
    dff3_out = 1'h0;
    dff4_out = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkLfsr5

