//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 10:25:16 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_output                     O     2
// RDY_get_output                 O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_output_a                   I     1
// get_output_b                   I     1
//
// Combinational paths from inputs to outputs:
//   (get_output_a, get_output_b) -> get_output
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkHalfAdder(CLK,
		   RST_N,

		   get_output_a,
		   get_output_b,
		   get_output,
		   RDY_get_output);
  input  CLK;
  input  RST_N;

  // value method get_output
  input  get_output_a;
  input  get_output_b;
  output [1 : 0] get_output;
  output RDY_get_output;

  // signals for module outputs
  wire [1 : 0] get_output;
  wire RDY_get_output;

  // remaining internal signals
  wire x__h20, x__h27;

  // value method get_output
  assign get_output = { x__h20, x__h27 } ;
  assign RDY_get_output = 1'd1 ;

  // remaining internal signals
  assign x__h20 = get_output_a | get_output_b ;
  assign x__h27 = get_output_a & get_output_b ;
endmodule  // mkHalfAdder

