//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 16:34:03 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_update                     O     1 const
// z                              O     1
// RDY_z                          O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// update_x                       I     1
// EN_update                      I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkExamsECE241(CLK,
		     RST_N,

		     update_x,
		     EN_update,
		     RDY_update,

		     z,
		     RDY_z);
  input  CLK;
  input  RST_N;

  // action method update
  input  update_x;
  input  EN_update;
  output RDY_update;

  // value method z
  output z;
  output RDY_z;

  // signals for module outputs
  wire RDY_update, RDY_z, z;

  // register dff0_q
  reg dff0_q;
  wire dff0_q$D_IN, dff0_q$EN;

  // register dff1_q
  reg dff1_q;
  wire dff1_q$D_IN, dff1_q$EN;

  // register dff2_q
  reg dff2_q;
  wire dff2_q$D_IN, dff2_q$EN;

  // remaining internal signals
  wire x__h279, x__h280, y__h244, y__h265;

  // action method update
  assign RDY_update = 1'd1 ;

  // value method z
  assign z = ~x__h279 ;
  assign RDY_z = 1'd1 ;

  // register dff0_q
  assign dff0_q$D_IN = update_x ^ dff0_q ;
  assign dff0_q$EN = EN_update ;

  // register dff1_q
  assign dff1_q$D_IN = update_x & y__h244 ;
  assign dff1_q$EN = EN_update ;

  // register dff2_q
  assign dff2_q$D_IN = update_x | y__h265 ;
  assign dff2_q$EN = EN_update ;

  // remaining internal signals
  assign x__h279 = x__h280 | dff2_q ;
  assign x__h280 = dff0_q | dff1_q ;
  assign y__h244 = ~dff1_q ;
  assign y__h265 = ~dff2_q ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        dff0_q <= `BSV_ASSIGNMENT_DELAY 1'd0;
	dff1_q <= `BSV_ASSIGNMENT_DELAY 1'd0;
	dff2_q <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (dff0_q$EN) dff0_q <= `BSV_ASSIGNMENT_DELAY dff0_q$D_IN;
	if (dff1_q$EN) dff1_q <= `BSV_ASSIGNMENT_DELAY dff1_q$D_IN;
	if (dff2_q$EN) dff2_q <= `BSV_ASSIGNMENT_DELAY dff2_q$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    dff0_q = 1'h0;
    dff1_q = 1'h0;
    dff2_q = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkExamsECE241

