//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 17:08:31 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// q                              O     4 reg
// RDY_q                          O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCounter15(CLK,
		   RST_N,

		   q,
		   RDY_q);
  input  CLK;
  input  RST_N;

  // value method q
  output [3 : 0] q;
  output RDY_q;

  // signals for module outputs
  wire [3 : 0] q;
  wire RDY_q;

  // register counter_reg
  reg [3 : 0] counter_reg;
  wire [3 : 0] counter_reg$D_IN;
  wire counter_reg$EN;

  // value method q
  assign q = counter_reg ;
  assign RDY_q = 1'd1 ;

  // register counter_reg
  assign counter_reg$D_IN = counter_reg + 4'd1 ;
  assign counter_reg$EN = 1'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        counter_reg <= `BSV_ASSIGNMENT_DELAY 4'd0;
      end
    else
      begin
        if (counter_reg$EN)
	  counter_reg <= `BSV_ASSIGNMENT_DELAY counter_reg$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    counter_reg = 4'hA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCounter15

