//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Mon Apr  6 22:13:18 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_p1y                        O     1
// RDY_get_p1y                    O     1 const
// get_p2y                        O     1
// RDY_get_p2y                    O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_p1y_p1a                    I     1
// get_p1y_p1b                    I     1
// get_p1y_p1c                    I     1
// get_p1y_p1d                    I     1
// get_p1y_p1e                    I     1
// get_p1y_p1f                    I     1
// get_p2y_p2a                    I     1
// get_p2y_p2b                    I     1
// get_p2y_p2c                    I     1
// get_p2y_p2d                    I     1
//
// Combinational paths from inputs to outputs:
//   (get_p1y_p1a,
//    get_p1y_p1b,
//    get_p1y_p1c,
//    get_p1y_p1d,
//    get_p1y_p1e,
//    get_p1y_p1f) -> get_p1y
//   (get_p2y_p2a, get_p2y_p2b, get_p2y_p2c, get_p2y_p2d) -> get_p2y
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkIC7458(CLK,
		RST_N,

		get_p1y_p1a,
		get_p1y_p1b,
		get_p1y_p1c,
		get_p1y_p1d,
		get_p1y_p1e,
		get_p1y_p1f,
		get_p1y,
		RDY_get_p1y,

		get_p2y_p2a,
		get_p2y_p2b,
		get_p2y_p2c,
		get_p2y_p2d,
		get_p2y,
		RDY_get_p2y);
  input  CLK;
  input  RST_N;

  // value method get_p1y
  input  get_p1y_p1a;
  input  get_p1y_p1b;
  input  get_p1y_p1c;
  input  get_p1y_p1d;
  input  get_p1y_p1e;
  input  get_p1y_p1f;
  output get_p1y;
  output RDY_get_p1y;

  // value method get_p2y
  input  get_p2y_p2a;
  input  get_p2y_p2b;
  input  get_p2y_p2c;
  input  get_p2y_p2d;
  output get_p2y;
  output RDY_get_p2y;

  // signals for module outputs
  wire RDY_get_p1y, RDY_get_p2y, get_p1y, get_p2y;

  // remaining internal signals
  wire p1_abc__h32, p1_def__h33, p2_ab__h69, p2_cd__h70, x__h45, x__h57;

  // value method get_p1y
  assign get_p1y = p1_abc__h32 | p1_def__h33 ;
  assign RDY_get_p1y = 1'd1 ;

  // value method get_p2y
  assign get_p2y = p2_ab__h69 | p2_cd__h70 ;
  assign RDY_get_p2y = 1'd1 ;

  // remaining internal signals
  assign p1_abc__h32 = x__h45 & get_p1y_p1c ;
  assign p1_def__h33 = x__h57 & get_p1y_p1f ;
  assign p2_ab__h69 = get_p2y_p2a & get_p2y_p2b ;
  assign p2_cd__h70 = get_p2y_p2c & get_p2y_p2d ;
  assign x__h45 = get_p1y_p1a & get_p1y_p1b ;
  assign x__h57 = get_p1y_p1d & get_p1y_p1e ;
endmodule  // mkIC7458

