//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 18:14:17 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_update                     O     1 const
// q                              O     4 reg
// RDY_q                          O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// update_load                    I     1
// update_ena                     I     1
// update_data                    I     4
// EN_update                      I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkShift4(CLK,
		RST_N,

		update_load,
		update_ena,
		update_data,
		EN_update,
		RDY_update,

		q,
		RDY_q);
  input  CLK;
  input  RST_N;

  // action method update
  input  update_load;
  input  update_ena;
  input  [3 : 0] update_data;
  input  EN_update;
  output RDY_update;

  // value method q
  output [3 : 0] q;
  output RDY_q;

  // signals for module outputs
  wire [3 : 0] q;
  wire RDY_q, RDY_update;

  // register shift_reg
  reg [3 : 0] shift_reg;
  wire [3 : 0] shift_reg$D_IN;
  wire shift_reg$EN;

  // remaining internal signals
  wire [3 : 0] x__h88;

  // action method update
  assign RDY_update = 1'd1 ;

  // value method q
  assign q = shift_reg ;
  assign RDY_q = 1'd1 ;

  // register shift_reg
  assign shift_reg$D_IN = update_load ? update_data : x__h88 ;
  assign shift_reg$EN = EN_update && (update_load || update_ena) ;

  // remaining internal signals
  assign x__h88 = { 1'b0, shift_reg[3:1] } ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        shift_reg <= `BSV_ASSIGNMENT_DELAY 4'd0;
      end
    else
      begin
        if (shift_reg$EN) shift_reg <= `BSV_ASSIGNMENT_DELAY shift_reg$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    shift_reg = 4'hA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkShift4

