//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 09:53:39 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_mux_output                 O    16
// RDY_get_mux_output             O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_mux_output_a               I    16
// get_mux_output_b               I    16
// get_mux_output_c               I    16
// get_mux_output_d               I    16
// get_mux_output_e               I    16
// get_mux_output_f               I    16
// get_mux_output_g               I    16
// get_mux_output_h               I    16
// get_mux_output_i               I    16
// get_mux_output_sel             I     4
//
// Combinational paths from inputs to outputs:
//   (get_mux_output_a,
//    get_mux_output_b,
//    get_mux_output_c,
//    get_mux_output_d,
//    get_mux_output_e,
//    get_mux_output_f,
//    get_mux_output_g,
//    get_mux_output_h,
//    get_mux_output_i,
//    get_mux_output_sel) -> get_mux_output
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMux9x1Vector(CLK,
		      RST_N,

		      get_mux_output_a,
		      get_mux_output_b,
		      get_mux_output_c,
		      get_mux_output_d,
		      get_mux_output_e,
		      get_mux_output_f,
		      get_mux_output_g,
		      get_mux_output_h,
		      get_mux_output_i,
		      get_mux_output_sel,
		      get_mux_output,
		      RDY_get_mux_output);
  input  CLK;
  input  RST_N;

  // value method get_mux_output
  input  [15 : 0] get_mux_output_a;
  input  [15 : 0] get_mux_output_b;
  input  [15 : 0] get_mux_output_c;
  input  [15 : 0] get_mux_output_d;
  input  [15 : 0] get_mux_output_e;
  input  [15 : 0] get_mux_output_f;
  input  [15 : 0] get_mux_output_g;
  input  [15 : 0] get_mux_output_h;
  input  [15 : 0] get_mux_output_i;
  input  [3 : 0] get_mux_output_sel;
  output [15 : 0] get_mux_output;
  output RDY_get_mux_output;

  // signals for module outputs
  reg [15 : 0] get_mux_output;
  wire RDY_get_mux_output;

  // value method get_mux_output
  always@(get_mux_output_sel or
	  get_mux_output_a or
	  get_mux_output_b or
	  get_mux_output_c or
	  get_mux_output_d or
	  get_mux_output_e or
	  get_mux_output_f or
	  get_mux_output_g or get_mux_output_h or get_mux_output_i)
  begin
    case (get_mux_output_sel)
      4'd0: get_mux_output = get_mux_output_a;
      4'd1: get_mux_output = get_mux_output_b;
      4'd2: get_mux_output = get_mux_output_c;
      4'd3: get_mux_output = get_mux_output_d;
      4'd4: get_mux_output = get_mux_output_e;
      4'd5: get_mux_output = get_mux_output_f;
      4'd6: get_mux_output = get_mux_output_g;
      4'd7: get_mux_output = get_mux_output_h;
      4'd8: get_mux_output = get_mux_output_i;
      default: get_mux_output = 16'b0;
    endcase
  end
  assign RDY_get_mux_output = 1'd1 ;
endmodule  // mkMux9x1Vector

