//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Mon Apr  6 21:56:44 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_xnor                       O     1
// RDY_get_xnor                   O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_xnor_x                     I     1
// get_xnor_y                     I     1
//
// Combinational paths from inputs to outputs:
//   (get_xnor_x, get_xnor_y) -> get_xnor
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkXnor(CLK,
	      RST_N,

	      get_xnor_x,
	      get_xnor_y,
	      get_xnor,
	      RDY_get_xnor);
  input  CLK;
  input  RST_N;

  // value method get_xnor
  input  get_xnor_x;
  input  get_xnor_y;
  output get_xnor;
  output RDY_get_xnor;

  // signals for module outputs
  wire RDY_get_xnor, get_xnor;

  // value method get_xnor
  assign get_xnor = ~(get_xnor_x ^ get_xnor_y) ;
  assign RDY_get_xnor = 1'd1 ;
endmodule  // mkXnor

