//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 14:54:22 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_step                       O     1 const
// outputs                        O     3 reg
// RDY_outputs                    O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// step_l                         I     1
// step_r0                        I     1
// step_r1                        I     1
// step_r2                        I     1
// EN_step                        I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMt2015MuxDFF(CLK,
		      RST_N,

		      step_l,
		      step_r0,
		      step_r1,
		      step_r2,
		      EN_step,
		      RDY_step,

		      outputs,
		      RDY_outputs);
  input  CLK;
  input  RST_N;

  // action method step
  input  step_l;
  input  step_r0;
  input  step_r1;
  input  step_r2;
  input  EN_step;
  output RDY_step;

  // value method outputs
  output [2 : 0] outputs;
  output RDY_outputs;

  // signals for module outputs
  wire [2 : 0] outputs;
  wire RDY_outputs, RDY_step;

  // register dff0_q_reg
  reg dff0_q_reg;
  wire dff0_q_reg$D_IN, dff0_q_reg$EN;

  // register dff1_q_reg
  reg dff1_q_reg;
  wire dff1_q_reg$D_IN, dff1_q_reg$EN;

  // register dff2_q_reg
  reg dff2_q_reg;
  wire dff2_q_reg$D_IN, dff2_q_reg$EN;

  // remaining internal signals
  wire xor_val__h249;

  // action method step
  assign RDY_step = 1'd1 ;

  // value method outputs
  assign outputs = { dff2_q_reg, dff1_q_reg, dff0_q_reg } ;
  assign RDY_outputs = 1'd1 ;

  // register dff0_q_reg
  assign dff0_q_reg$D_IN = step_l ? step_r0 : dff2_q_reg ;
  assign dff0_q_reg$EN = EN_step ;

  // register dff1_q_reg
  assign dff1_q_reg$D_IN = step_l ? step_r1 : dff0_q_reg ;
  assign dff1_q_reg$EN = EN_step ;

  // register dff2_q_reg
  assign dff2_q_reg$D_IN = step_l ? step_r2 : xor_val__h249 ;
  assign dff2_q_reg$EN = EN_step ;

  // remaining internal signals
  assign xor_val__h249 = dff1_q_reg ^ dff2_q_reg ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        dff0_q_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	dff1_q_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	dff2_q_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (dff0_q_reg$EN)
	  dff0_q_reg <= `BSV_ASSIGNMENT_DELAY dff0_q_reg$D_IN;
	if (dff1_q_reg$EN)
	  dff1_q_reg <= `BSV_ASSIGNMENT_DELAY dff1_q_reg$D_IN;
	if (dff2_q_reg$EN)
	  dff2_q_reg <= `BSV_ASSIGNMENT_DELAY dff2_q_reg$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    dff0_q_reg = 1'h0;
    dff1_q_reg = 1'h0;
    dff2_q_reg = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkMt2015MuxDFF

