//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 09:24:32 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_mux21_output               O     1
// RDY_get_mux21_output           O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_mux21_output_x             I     1
// get_mux21_output_y             I     1
// get_mux21_output_sel           I     1
//
// Combinational paths from inputs to outputs:
//   (get_mux21_output_x,
//    get_mux21_output_y,
//    get_mux21_output_sel) -> get_mux21_output
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMux2x1(CLK,
		RST_N,

		get_mux21_output_x,
		get_mux21_output_y,
		get_mux21_output_sel,
		get_mux21_output,
		RDY_get_mux21_output);
  input  CLK;
  input  RST_N;

  // value method get_mux21_output
  input  get_mux21_output_x;
  input  get_mux21_output_y;
  input  get_mux21_output_sel;
  output get_mux21_output;
  output RDY_get_mux21_output;

  // signals for module outputs
  wire RDY_get_mux21_output, get_mux21_output;

  // value method get_mux21_output
  assign get_mux21_output =
	     get_mux21_output_sel ? get_mux21_output_y : get_mux21_output_x ;
  assign RDY_get_mux21_output = 1'd1 ;
endmodule  // mkMux2x1

