//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 10:35:23 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_output                     O     2
// RDY_get_output                 O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_output_a                   I     1
// get_output_b                   I     1
// get_output_cin                 I     1
//
// Combinational paths from inputs to outputs:
//   (get_output_a, get_output_b, get_output_cin) -> get_output
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFullAdder(CLK,
		   RST_N,

		   get_output_a,
		   get_output_b,
		   get_output_cin,
		   get_output,
		   RDY_get_output);
  input  CLK;
  input  RST_N;

  // value method get_output
  input  get_output_a;
  input  get_output_b;
  input  get_output_cin;
  output [1 : 0] get_output;
  output RDY_get_output;

  // signals for module outputs
  wire [1 : 0] get_output;
  wire RDY_get_output;

  // remaining internal signals
  wire x__h21, x__h38, x__h41, x__h53, x__h55, y__h54, y__h56;

  // value method get_output
  assign get_output = { x__h21, x__h41 } ;
  assign RDY_get_output = 1'd1 ;

  // remaining internal signals
  assign x__h21 = x__h38 ^ get_output_cin ;
  assign x__h38 = get_output_a ^ get_output_b ;
  assign x__h41 = x__h53 | y__h54 ;
  assign x__h53 = x__h55 | y__h56 ;
  assign x__h55 = get_output_a & get_output_b ;
  assign y__h54 = get_output_a & get_output_cin ;
  assign y__h56 = get_output_b & get_output_cin ;
endmodule  // mkFullAdder

