//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Wed Apr  8 11:31:18 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_step                       O     1 const
// out                            O     1 reg
// RDY_out                        O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// step_reset                     I     1
// step_in_bit                    I     1
// EN_step                        I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFsm1_sync(CLK,
		   RST_N,

		   step_reset,
		   step_in_bit,
		   EN_step,
		   RDY_step,

		   out,
		   RDY_out);
  input  CLK;
  input  RST_N;

  // action method step
  input  step_reset;
  input  step_in_bit;
  input  EN_step;
  output RDY_step;

  // value method out
  output out;
  output RDY_out;

  // signals for module outputs
  wire RDY_out, RDY_step, out;

  // register state
  reg state;
  wire state$D_IN, state$EN;

  // action method step
  assign RDY_step = 1'd1 ;

  // value method out
  assign out = state ;
  assign RDY_out = 1'd1 ;

  // register state
  assign state$D_IN = step_reset || !(state ^ step_in_bit) ;
  assign state$EN = EN_step ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        state <= `BSV_ASSIGNMENT_DELAY 1'd1;
      end
    else
      begin
        if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    state = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkFsm1_sync

