//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 11:06:51 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_sum                        O     4
// RDY_get_sum                    O     1 const
// get_cout                       O     4
// RDY_get_cout                   O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_sum_a                      I     4
// get_sum_b                      I     4
// get_sum_cin                    I     4
// get_cout_a                     I     4
// get_cout_b                     I     4
// get_cout_cin                   I     4
//
// Combinational paths from inputs to outputs:
//   (get_sum_a, get_sum_b, get_sum_cin) -> get_sum
//   (get_cout_a, get_cout_b, get_cout_cin) -> get_cout
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRCA(CLK,
	     RST_N,

	     get_sum_a,
	     get_sum_b,
	     get_sum_cin,
	     get_sum,
	     RDY_get_sum,

	     get_cout_a,
	     get_cout_b,
	     get_cout_cin,
	     get_cout,
	     RDY_get_cout);
  input  CLK;
  input  RST_N;

  // value method get_sum
  input  [3 : 0] get_sum_a;
  input  [3 : 0] get_sum_b;
  input  [3 : 0] get_sum_cin;
  output [3 : 0] get_sum;
  output RDY_get_sum;

  // value method get_cout
  input  [3 : 0] get_cout_a;
  input  [3 : 0] get_cout_b;
  input  [3 : 0] get_cout_cin;
  output [3 : 0] get_cout;
  output RDY_get_cout;

  // signals for module outputs
  wire [3 : 0] get_cout, get_sum;
  wire RDY_get_cout, RDY_get_sum;

  // remaining internal signals
  wire c__h734,
       c__h802,
       c__h870,
       c__h938,
       cin__h390,
       cin__h456,
       cin__h525,
       s__h391,
       s__h457,
       s__h526,
       s__h595,
       x__h404,
       x__h470,
       x__h472,
       x__h539,
       x__h541,
       x__h608,
       x__h610,
       x__h681,
       x__h693,
       x__h705,
       x__h746,
       x__h748,
       x__h814,
       x__h816,
       x__h882,
       x__h884,
       x__h950,
       x__h952,
       y__h471,
       y__h473,
       y__h540,
       y__h542,
       y__h609,
       y__h611,
       y__h747,
       y__h749,
       y__h815,
       y__h817,
       y__h883,
       y__h885,
       y__h951,
       y__h953;

  // value method get_sum
  assign get_sum = { s__h391, s__h457, s__h526, s__h595 } ;
  assign RDY_get_sum = 1'd1 ;

  // value method get_cout
  assign get_cout = { c__h734, c__h802, c__h870, c__h938 } ;
  assign RDY_get_cout = 1'd1 ;

  // remaining internal signals
  assign c__h734 = x__h746 | y__h747 ;
  assign c__h802 = x__h814 | y__h815 ;
  assign c__h870 = x__h882 | y__h883 ;
  assign c__h938 = x__h950 | y__h951 ;
  assign cin__h390 = x__h470 | y__h471 ;
  assign cin__h456 = x__h539 | y__h540 ;
  assign cin__h525 = x__h608 | y__h609 ;
  assign s__h391 = x__h404 ^ cin__h390 ;
  assign s__h457 = x__h681 ^ cin__h456 ;
  assign s__h526 = x__h693 ^ cin__h525 ;
  assign s__h595 = x__h705 ^ get_sum_cin[0] ;
  assign x__h404 = get_sum_a[3] ^ get_sum_b[3] ;
  assign x__h470 = x__h472 | y__h473 ;
  assign x__h472 = get_sum_a[2] & get_sum_b[2] ;
  assign x__h539 = x__h541 | y__h542 ;
  assign x__h541 = get_sum_a[1] & get_sum_b[1] ;
  assign x__h608 = x__h610 | y__h611 ;
  assign x__h610 = get_sum_a[0] & get_sum_b[0] ;
  assign x__h681 = get_sum_a[2] ^ get_sum_b[2] ;
  assign x__h693 = get_sum_a[1] ^ get_sum_b[1] ;
  assign x__h705 = get_sum_a[0] ^ get_sum_b[0] ;
  assign x__h746 = x__h748 | y__h749 ;
  assign x__h748 = get_cout_a[3] & get_cout_b[3] ;
  assign x__h814 = x__h816 | y__h817 ;
  assign x__h816 = get_cout_a[2] & get_cout_b[2] ;
  assign x__h882 = x__h884 | y__h885 ;
  assign x__h884 = get_cout_a[1] & get_cout_b[1] ;
  assign x__h950 = x__h952 | y__h953 ;
  assign x__h952 = get_cout_a[0] & get_cout_b[0] ;
  assign y__h471 = get_sum_a[2] & cin__h456 ;
  assign y__h473 = get_sum_b[2] & cin__h456 ;
  assign y__h540 = get_sum_a[1] & cin__h525 ;
  assign y__h542 = get_sum_b[1] & cin__h525 ;
  assign y__h609 = get_sum_a[0] & get_sum_cin[0] ;
  assign y__h611 = get_sum_b[0] & get_sum_cin[0] ;
  assign y__h747 = get_cout_a[3] & c__h802 ;
  assign y__h749 = get_cout_b[3] & c__h802 ;
  assign y__h815 = get_cout_a[2] & c__h870 ;
  assign y__h817 = get_cout_b[2] & c__h870 ;
  assign y__h883 = get_cout_a[1] & c__h938 ;
  assign y__h885 = get_cout_b[1] & c__h938 ;
  assign y__h951 = get_cout_a[0] & get_cout_cin[0] ;
  assign y__h953 = get_cout_b[0] & get_cout_cin[0] ;
endmodule  // mkRCA

