//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Mon Apr  6 21:34:27 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_and                        O     1
// RDY_get_and                    O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_and_x                      I     1
// get_and_y                      I     1
//
// Combinational paths from inputs to outputs:
//   (get_and_x, get_and_y) -> get_and
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkAnd(CLK,
	     RST_N,

	     get_and_x,
	     get_and_y,
	     get_and,
	     RDY_get_and);
  input  CLK;
  input  RST_N;

  // value method get_and
  input  get_and_x;
  input  get_and_y;
  output get_and;
  output RDY_get_and;

  // signals for module outputs
  wire RDY_get_and, get_and;

  // value method get_and
  assign get_and = get_and_x & get_and_y ;
  assign RDY_get_and = 1'd1 ;
endmodule  // mkAnd

