//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Tue Apr  7 10:09:10 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_out                        O     4
// RDY_get_out                    O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_out_inputs                 I  1024
// get_out_sel                    I     8
//
// Combinational paths from inputs to outputs:
//   (get_out_inputs, get_out_sel) -> get_out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMux256x1Vector(CLK,
			RST_N,

			get_out_inputs,
			get_out_sel,
			get_out,
			RDY_get_out);
  input  CLK;
  input  RST_N;

  // value method get_out
  input  [1023 : 0] get_out_inputs;
  input  [7 : 0] get_out_sel;
  output [3 : 0] get_out;
  output RDY_get_out;

  // signals for module outputs
  reg [3 : 0] get_out;
  wire RDY_get_out;

  // value method get_out
  always@(get_out_sel or get_out_inputs)
  begin
    case (get_out_sel)
      8'd0: get_out = get_out_inputs[3:0];
      8'd1: get_out = get_out_inputs[7:4];
      8'd2: get_out = get_out_inputs[11:8];
      8'd3: get_out = get_out_inputs[15:12];
      8'd4: get_out = get_out_inputs[19:16];
      8'd5: get_out = get_out_inputs[23:20];
      8'd6: get_out = get_out_inputs[27:24];
      8'd7: get_out = get_out_inputs[31:28];
      8'd8: get_out = get_out_inputs[35:32];
      8'd9: get_out = get_out_inputs[39:36];
      8'd10: get_out = get_out_inputs[43:40];
      8'd11: get_out = get_out_inputs[47:44];
      8'd12: get_out = get_out_inputs[51:48];
      8'd13: get_out = get_out_inputs[55:52];
      8'd14: get_out = get_out_inputs[59:56];
      8'd15: get_out = get_out_inputs[63:60];
      8'd16: get_out = get_out_inputs[67:64];
      8'd17: get_out = get_out_inputs[71:68];
      8'd18: get_out = get_out_inputs[75:72];
      8'd19: get_out = get_out_inputs[79:76];
      8'd20: get_out = get_out_inputs[83:80];
      8'd21: get_out = get_out_inputs[87:84];
      8'd22: get_out = get_out_inputs[91:88];
      8'd23: get_out = get_out_inputs[95:92];
      8'd24: get_out = get_out_inputs[99:96];
      8'd25: get_out = get_out_inputs[103:100];
      8'd26: get_out = get_out_inputs[107:104];
      8'd27: get_out = get_out_inputs[111:108];
      8'd28: get_out = get_out_inputs[115:112];
      8'd29: get_out = get_out_inputs[119:116];
      8'd30: get_out = get_out_inputs[123:120];
      8'd31: get_out = get_out_inputs[127:124];
      8'd32: get_out = get_out_inputs[131:128];
      8'd33: get_out = get_out_inputs[135:132];
      8'd34: get_out = get_out_inputs[139:136];
      8'd35: get_out = get_out_inputs[143:140];
      8'd36: get_out = get_out_inputs[147:144];
      8'd37: get_out = get_out_inputs[151:148];
      8'd38: get_out = get_out_inputs[155:152];
      8'd39: get_out = get_out_inputs[159:156];
      8'd40: get_out = get_out_inputs[163:160];
      8'd41: get_out = get_out_inputs[167:164];
      8'd42: get_out = get_out_inputs[171:168];
      8'd43: get_out = get_out_inputs[175:172];
      8'd44: get_out = get_out_inputs[179:176];
      8'd45: get_out = get_out_inputs[183:180];
      8'd46: get_out = get_out_inputs[187:184];
      8'd47: get_out = get_out_inputs[191:188];
      8'd48: get_out = get_out_inputs[195:192];
      8'd49: get_out = get_out_inputs[199:196];
      8'd50: get_out = get_out_inputs[203:200];
      8'd51: get_out = get_out_inputs[207:204];
      8'd52: get_out = get_out_inputs[211:208];
      8'd53: get_out = get_out_inputs[215:212];
      8'd54: get_out = get_out_inputs[219:216];
      8'd55: get_out = get_out_inputs[223:220];
      8'd56: get_out = get_out_inputs[227:224];
      8'd57: get_out = get_out_inputs[231:228];
      8'd58: get_out = get_out_inputs[235:232];
      8'd59: get_out = get_out_inputs[239:236];
      8'd60: get_out = get_out_inputs[243:240];
      8'd61: get_out = get_out_inputs[247:244];
      8'd62: get_out = get_out_inputs[251:248];
      8'd63: get_out = get_out_inputs[255:252];
      8'd64: get_out = get_out_inputs[259:256];
      8'd65: get_out = get_out_inputs[263:260];
      8'd66: get_out = get_out_inputs[267:264];
      8'd67: get_out = get_out_inputs[271:268];
      8'd68: get_out = get_out_inputs[275:272];
      8'd69: get_out = get_out_inputs[279:276];
      8'd70: get_out = get_out_inputs[283:280];
      8'd71: get_out = get_out_inputs[287:284];
      8'd72: get_out = get_out_inputs[291:288];
      8'd73: get_out = get_out_inputs[295:292];
      8'd74: get_out = get_out_inputs[299:296];
      8'd75: get_out = get_out_inputs[303:300];
      8'd76: get_out = get_out_inputs[307:304];
      8'd77: get_out = get_out_inputs[311:308];
      8'd78: get_out = get_out_inputs[315:312];
      8'd79: get_out = get_out_inputs[319:316];
      8'd80: get_out = get_out_inputs[323:320];
      8'd81: get_out = get_out_inputs[327:324];
      8'd82: get_out = get_out_inputs[331:328];
      8'd83: get_out = get_out_inputs[335:332];
      8'd84: get_out = get_out_inputs[339:336];
      8'd85: get_out = get_out_inputs[343:340];
      8'd86: get_out = get_out_inputs[347:344];
      8'd87: get_out = get_out_inputs[351:348];
      8'd88: get_out = get_out_inputs[355:352];
      8'd89: get_out = get_out_inputs[359:356];
      8'd90: get_out = get_out_inputs[363:360];
      8'd91: get_out = get_out_inputs[367:364];
      8'd92: get_out = get_out_inputs[371:368];
      8'd93: get_out = get_out_inputs[375:372];
      8'd94: get_out = get_out_inputs[379:376];
      8'd95: get_out = get_out_inputs[383:380];
      8'd96: get_out = get_out_inputs[387:384];
      8'd97: get_out = get_out_inputs[391:388];
      8'd98: get_out = get_out_inputs[395:392];
      8'd99: get_out = get_out_inputs[399:396];
      8'd100: get_out = get_out_inputs[403:400];
      8'd101: get_out = get_out_inputs[407:404];
      8'd102: get_out = get_out_inputs[411:408];
      8'd103: get_out = get_out_inputs[415:412];
      8'd104: get_out = get_out_inputs[419:416];
      8'd105: get_out = get_out_inputs[423:420];
      8'd106: get_out = get_out_inputs[427:424];
      8'd107: get_out = get_out_inputs[431:428];
      8'd108: get_out = get_out_inputs[435:432];
      8'd109: get_out = get_out_inputs[439:436];
      8'd110: get_out = get_out_inputs[443:440];
      8'd111: get_out = get_out_inputs[447:444];
      8'd112: get_out = get_out_inputs[451:448];
      8'd113: get_out = get_out_inputs[455:452];
      8'd114: get_out = get_out_inputs[459:456];
      8'd115: get_out = get_out_inputs[463:460];
      8'd116: get_out = get_out_inputs[467:464];
      8'd117: get_out = get_out_inputs[471:468];
      8'd118: get_out = get_out_inputs[475:472];
      8'd119: get_out = get_out_inputs[479:476];
      8'd120: get_out = get_out_inputs[483:480];
      8'd121: get_out = get_out_inputs[487:484];
      8'd122: get_out = get_out_inputs[491:488];
      8'd123: get_out = get_out_inputs[495:492];
      8'd124: get_out = get_out_inputs[499:496];
      8'd125: get_out = get_out_inputs[503:500];
      8'd126: get_out = get_out_inputs[507:504];
      8'd127: get_out = get_out_inputs[511:508];
      8'd128: get_out = get_out_inputs[515:512];
      8'd129: get_out = get_out_inputs[519:516];
      8'd130: get_out = get_out_inputs[523:520];
      8'd131: get_out = get_out_inputs[527:524];
      8'd132: get_out = get_out_inputs[531:528];
      8'd133: get_out = get_out_inputs[535:532];
      8'd134: get_out = get_out_inputs[539:536];
      8'd135: get_out = get_out_inputs[543:540];
      8'd136: get_out = get_out_inputs[547:544];
      8'd137: get_out = get_out_inputs[551:548];
      8'd138: get_out = get_out_inputs[555:552];
      8'd139: get_out = get_out_inputs[559:556];
      8'd140: get_out = get_out_inputs[563:560];
      8'd141: get_out = get_out_inputs[567:564];
      8'd142: get_out = get_out_inputs[571:568];
      8'd143: get_out = get_out_inputs[575:572];
      8'd144: get_out = get_out_inputs[579:576];
      8'd145: get_out = get_out_inputs[583:580];
      8'd146: get_out = get_out_inputs[587:584];
      8'd147: get_out = get_out_inputs[591:588];
      8'd148: get_out = get_out_inputs[595:592];
      8'd149: get_out = get_out_inputs[599:596];
      8'd150: get_out = get_out_inputs[603:600];
      8'd151: get_out = get_out_inputs[607:604];
      8'd152: get_out = get_out_inputs[611:608];
      8'd153: get_out = get_out_inputs[615:612];
      8'd154: get_out = get_out_inputs[619:616];
      8'd155: get_out = get_out_inputs[623:620];
      8'd156: get_out = get_out_inputs[627:624];
      8'd157: get_out = get_out_inputs[631:628];
      8'd158: get_out = get_out_inputs[635:632];
      8'd159: get_out = get_out_inputs[639:636];
      8'd160: get_out = get_out_inputs[643:640];
      8'd161: get_out = get_out_inputs[647:644];
      8'd162: get_out = get_out_inputs[651:648];
      8'd163: get_out = get_out_inputs[655:652];
      8'd164: get_out = get_out_inputs[659:656];
      8'd165: get_out = get_out_inputs[663:660];
      8'd166: get_out = get_out_inputs[667:664];
      8'd167: get_out = get_out_inputs[671:668];
      8'd168: get_out = get_out_inputs[675:672];
      8'd169: get_out = get_out_inputs[679:676];
      8'd170: get_out = get_out_inputs[683:680];
      8'd171: get_out = get_out_inputs[687:684];
      8'd172: get_out = get_out_inputs[691:688];
      8'd173: get_out = get_out_inputs[695:692];
      8'd174: get_out = get_out_inputs[699:696];
      8'd175: get_out = get_out_inputs[703:700];
      8'd176: get_out = get_out_inputs[707:704];
      8'd177: get_out = get_out_inputs[711:708];
      8'd178: get_out = get_out_inputs[715:712];
      8'd179: get_out = get_out_inputs[719:716];
      8'd180: get_out = get_out_inputs[723:720];
      8'd181: get_out = get_out_inputs[727:724];
      8'd182: get_out = get_out_inputs[731:728];
      8'd183: get_out = get_out_inputs[735:732];
      8'd184: get_out = get_out_inputs[739:736];
      8'd185: get_out = get_out_inputs[743:740];
      8'd186: get_out = get_out_inputs[747:744];
      8'd187: get_out = get_out_inputs[751:748];
      8'd188: get_out = get_out_inputs[755:752];
      8'd189: get_out = get_out_inputs[759:756];
      8'd190: get_out = get_out_inputs[763:760];
      8'd191: get_out = get_out_inputs[767:764];
      8'd192: get_out = get_out_inputs[771:768];
      8'd193: get_out = get_out_inputs[775:772];
      8'd194: get_out = get_out_inputs[779:776];
      8'd195: get_out = get_out_inputs[783:780];
      8'd196: get_out = get_out_inputs[787:784];
      8'd197: get_out = get_out_inputs[791:788];
      8'd198: get_out = get_out_inputs[795:792];
      8'd199: get_out = get_out_inputs[799:796];
      8'd200: get_out = get_out_inputs[803:800];
      8'd201: get_out = get_out_inputs[807:804];
      8'd202: get_out = get_out_inputs[811:808];
      8'd203: get_out = get_out_inputs[815:812];
      8'd204: get_out = get_out_inputs[819:816];
      8'd205: get_out = get_out_inputs[823:820];
      8'd206: get_out = get_out_inputs[827:824];
      8'd207: get_out = get_out_inputs[831:828];
      8'd208: get_out = get_out_inputs[835:832];
      8'd209: get_out = get_out_inputs[839:836];
      8'd210: get_out = get_out_inputs[843:840];
      8'd211: get_out = get_out_inputs[847:844];
      8'd212: get_out = get_out_inputs[851:848];
      8'd213: get_out = get_out_inputs[855:852];
      8'd214: get_out = get_out_inputs[859:856];
      8'd215: get_out = get_out_inputs[863:860];
      8'd216: get_out = get_out_inputs[867:864];
      8'd217: get_out = get_out_inputs[871:868];
      8'd218: get_out = get_out_inputs[875:872];
      8'd219: get_out = get_out_inputs[879:876];
      8'd220: get_out = get_out_inputs[883:880];
      8'd221: get_out = get_out_inputs[887:884];
      8'd222: get_out = get_out_inputs[891:888];
      8'd223: get_out = get_out_inputs[895:892];
      8'd224: get_out = get_out_inputs[899:896];
      8'd225: get_out = get_out_inputs[903:900];
      8'd226: get_out = get_out_inputs[907:904];
      8'd227: get_out = get_out_inputs[911:908];
      8'd228: get_out = get_out_inputs[915:912];
      8'd229: get_out = get_out_inputs[919:916];
      8'd230: get_out = get_out_inputs[923:920];
      8'd231: get_out = get_out_inputs[927:924];
      8'd232: get_out = get_out_inputs[931:928];
      8'd233: get_out = get_out_inputs[935:932];
      8'd234: get_out = get_out_inputs[939:936];
      8'd235: get_out = get_out_inputs[943:940];
      8'd236: get_out = get_out_inputs[947:944];
      8'd237: get_out = get_out_inputs[951:948];
      8'd238: get_out = get_out_inputs[955:952];
      8'd239: get_out = get_out_inputs[959:956];
      8'd240: get_out = get_out_inputs[963:960];
      8'd241: get_out = get_out_inputs[967:964];
      8'd242: get_out = get_out_inputs[971:968];
      8'd243: get_out = get_out_inputs[975:972];
      8'd244: get_out = get_out_inputs[979:976];
      8'd245: get_out = get_out_inputs[983:980];
      8'd246: get_out = get_out_inputs[987:984];
      8'd247: get_out = get_out_inputs[991:988];
      8'd248: get_out = get_out_inputs[995:992];
      8'd249: get_out = get_out_inputs[999:996];
      8'd250: get_out = get_out_inputs[1003:1000];
      8'd251: get_out = get_out_inputs[1007:1004];
      8'd252: get_out = get_out_inputs[1011:1008];
      8'd253: get_out = get_out_inputs[1015:1012];
      8'd254: get_out = get_out_inputs[1019:1016];
      8'd255: get_out = get_out_inputs[1023:1020];
    endcase
  end
  assign RDY_get_out = 1'd1 ;
endmodule  // mkMux256x1Vector

