//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Mon Apr  6 21:42:53 PDT 2026
//
//
// Ports:
// Name                         I/O  size props
// get_or                         O     1
// RDY_get_or                     O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// get_or_x                       I     1
// get_or_y                       I     1
//
// Combinational paths from inputs to outputs:
//   (get_or_x, get_or_y) -> get_or
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkOr(CLK,
	    RST_N,

	    get_or_x,
	    get_or_y,
	    get_or,
	    RDY_get_or);
  input  CLK;
  input  RST_N;

  // value method get_or
  input  get_or_x;
  input  get_or_y;
  output get_or;
  output RDY_get_or;

  // signals for module outputs
  wire RDY_get_or, get_or;

  // value method get_or
  assign get_or = get_or_x | get_or_y ;
  assign RDY_get_or = 1'd1 ;
endmodule  // mkOr

